color: null
fieldLayouts:
  39be10db-37ca-4c18-bcfc-dc6e5ca779eb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-15T20:15:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cd5cd84b-c658-499e-9dc0-f61b3e020d75
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-15T20:17:08+00:00'
            elementCondition: null
            fieldUid: 9388ce43-5c4b-4071-b904-538f472df8c1 # Introduction
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ba65171-5069-45cc-be9e-b1ae74796759
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 588e8d79-b5c3-4d01-81e0-cd4cada570ab
        userCondition: null
handle: about
hasTitleField: true
icon: ''
name: About
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
