color: null
fieldLayouts:
  5464d0be-3d89-4d89-88f8-cf7d37359205:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-15T19:48:46+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c80fb6b1-173b-4a78-8675-b67fb2929e26
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-15T20:12:33+00:00'
            elementCondition: null
            fieldUid: 5277367b-946d-401c-9255-b284d69533e1 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dbd1ddfa-3bda-4e05-9474-f73f2582b1bd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-15T20:12:33+00:00'
            elementCondition: null
            fieldUid: 9388ce43-5c4b-4071-b904-538f472df8c1 # Introduction
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15af7b6f-e841-45b6-a71d-fe83111bca12
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-15T20:12:33+00:00'
            elementCondition: null
            fieldUid: 8510d64d-58bd-48c5-9156-5961afec6661 # Main Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28c0f6eb-a325-49da-9913-0e256d04b599
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d629f409-c872-4691-8836-b99e7c3dee34
        userCondition: null
handle: homepage
hasTitleField: true
icon: house
name: Homepage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
