defaultPlacement: end
fieldLayouts:
  5e3cd178-61a5-4f83-9eef-bc35d4446a87:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-15T20:47:38+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 7f826539-94eb-40bc-a678-23586489cd4b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-15T20:48:59+00:00'
            elementCondition: null
            fieldUid: 5277367b-946d-401c-9255-b284d69533e1 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 897e9efc-a6bd-4fa3-951f-f909f2549805
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ae69d618-305d-4fe6-a88a-242c0f87b772
        userCondition: null
handle: destinations
name: Destinations
siteSettings:
  d5dcaa38-6d41-4085-8a03-17e1fd117536: # travel
    hasUrls: true
    template: destinations/_category.twig
    uriFormat: 'destinations/{slug}'
structure:
  maxLevels: null
  uid: 2e29664f-bc74-41cf-9f1a-dee3929fbfda
