defaultPlacement: end
fieldLayouts:
  a6490ed3-df78-4c54-9025-f5c8f8c6f64e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-15T22:26:18+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 713fa037-aceb-45e7-b159-e2de1bad6866
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e1e7159f-0cc9-4730-983e-bc5256090efd
        userCondition: null
handle: planning
name: Planning
siteSettings:
  d5dcaa38-6d41-4085-8a03-17e1fd117536: # travel
    hasUrls: true
    template: planning/_category.twig
    uriFormat: 'planning/{slug}'
structure:
  maxLevels: null
  uid: 26fc3ccd-8fc5-4a1d-8e57-c8e0bd9ebd9f
