defaultPlacement: end
fieldLayouts:
  8e695ebe-996c-4f7a-b3eb-9be1245a2216:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-15T20:48:04+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: c515c271-1bd6-4c88-a38c-f1c12dbff6da
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c92e6663-68ce-4713-a35d-1c4e4c256834
        userCondition: null
handle: region
name: Region
siteSettings:
  d5dcaa38-6d41-4085-8a03-17e1fd117536: # travel
    hasUrls: true
    template: region/_category.twig
    uriFormat: 'region/{slug}'
structure:
  maxLevels: null
  uid: 8eab22f5-b6f4-42ed-b6f4-99c15f5e8f4b
