altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  75a2323e-5870-4963-bff6-23383f6633bc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-15T23:09:13+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 5176ea9b-98ea-43e7-9ea3-29c673bbcae8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4f2dae8a-3efa-4e54-81b8-410792a9c7e1
        userCondition: null
fs: defaultImages
handle: defaultImages
name: 'Default Images'
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
