defaultPlacement: end
enableVersioning: true
entryTypes:
  - 60e6fb54-ebcd-49e0-98bc-8139a715b5db # Blog
handle: blog
maxAuthors: 1
name: Blog
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d5dcaa38-6d41-4085-8a03-17e1fd117536: # travel
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry.twig
    uriFormat: 'blog/{slug}'
type: channel
