defaultPlacement: end
enableVersioning: true
entryTypes:
  - 423a87c5-f04a-42f8-bef2-d5df70da6ede # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d5dcaa38-6d41-4085-8a03-17e1fd117536: # travel
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
